"""add folder position

Revision ID: 04987b21232e
Revises: 8a70008cd021
Create Date: 2026-02-17 18:43:24.459485

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04987b21232e"
down_revision: Union[str, Sequence[str], None] = "8a70008cd021"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("folders", sa.Column("position", sa.Integer(), nullable=True))
    op.execute(
        """
        WITH ordered AS (
            SELECT
                id,
                ROW_NUMBER() OVER (
                    PARTITION BY parent_id
                    ORDER BY name ASC, id ASC
                ) - 1 AS new_position
            FROM folders
        )
        UPDATE folders
        SET position = ordered.new_position
        FROM ordered
        WHERE folders.id = ordered.id
        """
    )
    op.alter_column("folders", "position", existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("folders", "position")
    # ### end Alembic commands ###
