"""add playlist table and playlist_videos association

Revision ID: 2fc0fcb4e8dc
Revises: 20260217_add_video_fts
Create Date: 2026-02-17 17:43:30.071556

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2fc0fcb4e8dc"
down_revision: Union[str, Sequence[str], None] = "20260217_add_video_fts"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlists",
        sa.Column("id", sa.String(length=36), nullable=False, comment="UUID as string"),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_playlists_name"), "playlists", ["name"], unique=False)
    op.create_table(
        "playlist_videos",
        sa.Column("playlist_id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=16), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("playlist_id", "video_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playlist_videos")
    op.drop_index(op.f("ix_playlists_name"), table_name="playlists")
    op.drop_table("playlists")
    # ### end Alembic commands ###
