"""add is_system and current_position to playlists

Revision ID: 8a70008cd021
Revises: 2fc0fcb4e8dc
Create Date: 2026-02-17 18:03:10.278450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a70008cd021'
down_revision: Union[str, Sequence[str], None] = '2fc0fcb4e8dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('playlists', sa.Column('current_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'current_position')
    op.drop_column('playlists', 'is_system')
    # ### end Alembic commands ###
