"""Create initial database schema

Revision ID: 992dacbe0482
Revises:
Create Date: 2025-08-19 21:15:29.782797

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "992dacbe0482"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "folders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["folders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_folders_id"), "folders", ["id"], unique=False)
    op.create_table(
        "channels",
        sa.Column(
            "id",
            sa.String(length=32),
            nullable=False,
            comment="YouTube's Channel ID (e.g., UC_x5XG1OV2P6uZZ5FSM9Ttw)",
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("handle", sa.String(length=128), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.String(length=512), nullable=True),
        sa.Column(
            "uploads_playlist_id",
            sa.String(length=48),
            nullable=False,
            comment="The ID of the channel's 'uploads' playlist.",
        ),
        sa.Column("is_favorited", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("folder_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["folders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_channels_handle"), "channels", ["handle"], unique=True)
    op.create_table(
        "videos",
        sa.Column(
            "id",
            sa.String(length=16),
            nullable=False,
            comment="YouTube's Video ID (e.g., dQw4w9WgXcQ)",
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.String(length=512), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("is_favorited", sa.Boolean(), nullable=False),
        sa.Column("is_short", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("channel_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_videos_channel_id"), "videos", ["channel_id"], unique=False
    )
    op.create_index(
        op.f("ix_videos_published_at"), "videos", ["published_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_videos_published_at"), table_name="videos")
    op.drop_index(op.f("ix_videos_channel_id"), table_name="videos")
    op.drop_table("videos")
    op.drop_index(op.f("ix_channels_handle"), table_name="channels")
    op.drop_table("channels")
    op.drop_index(op.f("ix_folders_id"), table_name="folders")
    op.drop_table("folders")
    # ### end Alembic commands ###
