"""video add tags and is_watched

Revision ID: a67d3ea6e7b3
Revises: 992dacbe0482
Create Date: 2025-08-21 13:36:37.422341

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a67d3ea6e7b3"
down_revision: Union[str, Sequence[str], None] = "992dacbe0482"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "videos",
        sa.Column("is_watched", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "videos",
        sa.Column("yt_tags", sa.ARRAY(sa.Text()), server_default="{}", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("videos", "yt_tags")
    op.drop_column("videos", "is_watched")
    # ### end Alembic commands ###
