"""add folder icon string key

Revision ID: c8d6f904317b
Revises: 20260202_folder_tag_uuid
Create Date: 2026-02-12 17:43:31.265343

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c8d6f904317b"
down_revision: Union[str, Sequence[str], None] = "20260202_folder_tag_uuid"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "folders", sa.Column("icon_key", sa.String(length=255), nullable=True)
    )
    op.alter_column(
        "folders",
        "id",
        existing_type=sa.VARCHAR(length=36),
        comment="UUID as string",
        existing_nullable=False,
    )
    op.alter_column(
        "tags",
        "id",
        existing_type=sa.VARCHAR(length=36),
        comment="UUID as string",
        existing_nullable=False,
    )
    op.drop_constraint(op.f("uq_tags_name"), "tags", type_="unique")
    op.create_index(
        "ix_video_channel_published",
        "videos",
        ["channel_id", "published_at"],
        unique=False,
    )
    op.create_index("ix_video_is_favorited", "videos", ["is_favorited"], unique=False)
    op.create_index("ix_video_is_short", "videos", ["is_short"], unique=False)
    op.create_index("ix_video_is_watched", "videos", ["is_watched"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_video_is_watched", table_name="videos")
    op.drop_index("ix_video_is_short", table_name="videos")
    op.drop_index("ix_video_is_favorited", table_name="videos")
    op.drop_index("ix_video_channel_published", table_name="videos")
    op.create_unique_constraint(
        op.f("uq_tags_name"), "tags", ["name"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "tags",
        "id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="UUID as string",
        existing_nullable=False,
    )
    op.alter_column(
        "folders",
        "id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="UUID as string",
        existing_nullable=False,
    )
    op.drop_column("folders", "icon_key")
    # ### end Alembic commands ###
